name: CI

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read

    strategy:
      fail-fast: true
      matrix:
        node:
          - 20
          - 22
          - 24
          - 26

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@f27a68a73a799c79d7158cf4a98d7e3d5e8e23be # v1.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Run test
        run: pnpm run test

  code-checks:
    name: Code checks
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@f27a68a73a799c79d7158cf4a98d7e3d5e8e23be # v1.1.0

      - name: Run build
        run: pnpm run build

      - name: Run format:check
        run: pnpm run format:check

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
