name: CI

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Run test
        run: pnpm run test

  code-check:
    name: Code check (${{ matrix.script }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        script: ['build', 'typecheck', 'format']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs: [test, code-check]
    env:
      FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
    steps:
      - name: Check for failure
        run: |
          echo $FAILURE
          if [ "$FAILURE" = "false" ]; then
            exit 0
          else
            exit 1
          fi
